export interface GeoSubdivision {
    code: string
    name: string
}

export interface GeoCountry {
    code: string
    name: string
    flag: string
    subdivisions: GeoSubdivision[]
}

export const GEO_COUNTRIES: GeoCountry[] = [
    {
        code: 'BR', name: 'Brasil', flag: '🇧🇷',
        subdivisions: [
            { code: 'AC', name: 'Acre' }, { code: 'AL', name: 'Alagoas' }, { code: 'AP', name: 'Amapá' },
            { code: 'AM', name: 'Amazonas' }, { code: 'BA', name: 'Bahia' }, { code: 'CE', name: 'Ceará' },
            { code: 'DF', name: 'Distrito Federal' }, { code: 'ES', name: 'Espírito Santo' }, { code: 'GO', name: 'Goiás' },
            { code: 'MA', name: 'Maranhão' }, { code: 'MT', name: 'Mato Grosso' }, { code: 'MS', name: 'Mato Grosso do Sul' },
            { code: 'MG', name: 'Minas Gerais' }, { code: 'PA', name: 'Pará' }, { code: 'PB', name: 'Paraíba' },
            { code: 'PR', name: 'Paraná' }, { code: 'PE', name: 'Pernambuco' }, { code: 'PI', name: 'Piauí' },
            { code: 'RJ', name: 'Rio de Janeiro' }, { code: 'RN', name: 'Rio Grande do Norte' },
            { code: 'RS', name: 'Rio Grande do Sul' }, { code: 'RO', name: 'Rondônia' }, { code: 'RR', name: 'Roraima' },
            { code: 'SC', name: 'Santa Catarina' }, { code: 'SP', name: 'São Paulo' },
            { code: 'SE', name: 'Sergipe' }, { code: 'TO', name: 'Tocantins' },
        ],
    },
    {
        code: 'US', name: 'Estados Unidos', flag: '🇺🇸',
        subdivisions: [
            { code: 'AL', name: 'Alabama' }, { code: 'AK', name: 'Alaska' }, { code: 'AZ', name: 'Arizona' },
            { code: 'AR', name: 'Arkansas' }, { code: 'CA', name: 'California' }, { code: 'CO', name: 'Colorado' },
            { code: 'CT', name: 'Connecticut' }, { code: 'DE', name: 'Delaware' }, { code: 'FL', name: 'Florida' },
            { code: 'GA', name: 'Georgia' }, { code: 'HI', name: 'Hawaii' }, { code: 'ID', name: 'Idaho' },
            { code: 'IL', name: 'Illinois' }, { code: 'IN', name: 'Indiana' }, { code: 'IA', name: 'Iowa' },
            { code: 'KS', name: 'Kansas' }, { code: 'KY', name: 'Kentucky' }, { code: 'LA', name: 'Louisiana' },
            { code: 'ME', name: 'Maine' }, { code: 'MD', name: 'Maryland' }, { code: 'MA', name: 'Massachusetts' },
            { code: 'MI', name: 'Michigan' }, { code: 'MN', name: 'Minnesota' }, { code: 'MS', name: 'Mississippi' },
            { code: 'MO', name: 'Missouri' }, { code: 'MT', name: 'Montana' }, { code: 'NE', name: 'Nebraska' },
            { code: 'NV', name: 'Nevada' }, { code: 'NH', name: 'New Hampshire' }, { code: 'NJ', name: 'New Jersey' },
            { code: 'NM', name: 'New Mexico' }, { code: 'NY', name: 'New York' }, { code: 'NC', name: 'North Carolina' },
            { code: 'ND', name: 'North Dakota' }, { code: 'OH', name: 'Ohio' }, { code: 'OK', name: 'Oklahoma' },
            { code: 'OR', name: 'Oregon' }, { code: 'PA', name: 'Pennsylvania' }, { code: 'RI', name: 'Rhode Island' },
            { code: 'SC', name: 'South Carolina' }, { code: 'SD', name: 'South Dakota' }, { code: 'TN', name: 'Tennessee' },
            { code: 'TX', name: 'Texas' }, { code: 'UT', name: 'Utah' }, { code: 'VT', name: 'Vermont' },
            { code: 'VA', name: 'Virginia' }, { code: 'WA', name: 'Washington' }, { code: 'WV', name: 'West Virginia' },
            { code: 'WI', name: 'Wisconsin' }, { code: 'WY', name: 'Wyoming' }, { code: 'DC', name: 'Washington D.C.' },
        ],
    },
    {
        code: 'CA', name: 'Canadá', flag: '🇨🇦',
        subdivisions: [
            { code: 'AB', name: 'Alberta' }, { code: 'BC', name: 'British Columbia' }, { code: 'MB', name: 'Manitoba' },
            { code: 'NB', name: 'New Brunswick' }, { code: 'NL', name: 'Newfoundland and Labrador' },
            { code: 'NS', name: 'Nova Scotia' }, { code: 'NT', name: 'Northwest Territories' },
            { code: 'NU', name: 'Nunavut' }, { code: 'ON', name: 'Ontario' }, { code: 'PE', name: 'Prince Edward Island' },
            { code: 'QC', name: 'Quebec' }, { code: 'SK', name: 'Saskatchewan' }, { code: 'YT', name: 'Yukon' },
        ],
    },
    {
        code: 'MX', name: 'México', flag: '🇲🇽',
        subdivisions: [
            { code: 'AGU', name: 'Aguascalientes' }, { code: 'BCN', name: 'Baja California' },
            { code: 'BCS', name: 'Baja California Sur' }, { code: 'CAM', name: 'Campeche' },
            { code: 'CHP', name: 'Chiapas' }, { code: 'CHH', name: 'Chihuahua' },
            { code: 'CMX', name: 'Ciudad de México' }, { code: 'COA', name: 'Coahuila' },
            { code: 'COL', name: 'Colima' }, { code: 'DUR', name: 'Durango' }, { code: 'GUA', name: 'Guanajuato' },
            { code: 'GRO', name: 'Guerrero' }, { code: 'HID', name: 'Hidalgo' }, { code: 'JAL', name: 'Jalisco' },
            { code: 'MEX', name: 'Estado de México' }, { code: 'MIC', name: 'Michoacán' },
            { code: 'MOR', name: 'Morelos' }, { code: 'NAY', name: 'Nayarit' }, { code: 'NLE', name: 'Nuevo León' },
            { code: 'OAX', name: 'Oaxaca' }, { code: 'PUE', name: 'Puebla' }, { code: 'QUE', name: 'Querétaro' },
            { code: 'ROO', name: 'Quintana Roo' }, { code: 'SLP', name: 'San Luis Potosí' },
            { code: 'SIN', name: 'Sinaloa' }, { code: 'SON', name: 'Sonora' }, { code: 'TAB', name: 'Tabasco' },
            { code: 'TAM', name: 'Tamaulipas' }, { code: 'TLA', name: 'Tlaxcala' },
            { code: 'VER', name: 'Veracruz' }, { code: 'YUC', name: 'Yucatán' }, { code: 'ZAC', name: 'Zacatecas' },
        ],
    },
    {
        code: 'AR', name: 'Argentina', flag: '🇦🇷',
        subdivisions: [
            { code: 'B', name: 'Buenos Aires (Provincia)' }, { code: 'C', name: 'Ciudad Autónoma de Buenos Aires' },
            { code: 'K', name: 'Catamarca' }, { code: 'H', name: 'Chaco' }, { code: 'U', name: 'Chubut' },
            { code: 'X', name: 'Córdoba' }, { code: 'W', name: 'Corrientes' }, { code: 'E', name: 'Entre Ríos' },
            { code: 'P', name: 'Formosa' }, { code: 'Y', name: 'Jujuy' }, { code: 'L', name: 'La Pampa' },
            { code: 'F', name: 'La Rioja' }, { code: 'M', name: 'Mendoza' }, { code: 'N', name: 'Misiones' },
            { code: 'Q', name: 'Neuquén' }, { code: 'R', name: 'Río Negro' }, { code: 'A', name: 'Salta' },
            { code: 'J', name: 'San Juan' }, { code: 'D', name: 'San Luis' }, { code: 'Z', name: 'Santa Cruz' },
            { code: 'S', name: 'Santa Fe' }, { code: 'G', name: 'Santiago del Estero' },
            { code: 'V', name: 'Tierra del Fuego' }, { code: 'T', name: 'Tucumán' },
        ],
    },
    {
        code: 'CL', name: 'Chile', flag: '🇨🇱',
        subdivisions: [
            { code: 'AP', name: 'Arica y Parinacota' }, { code: 'TA', name: 'Tarapacá' },
            { code: 'AN', name: 'Antofagasta' }, { code: 'AT', name: 'Atacama' }, { code: 'CO', name: 'Coquimbo' },
            { code: 'VS', name: 'Valparaíso' }, { code: 'RM', name: 'Región Metropolitana de Santiago' },
            { code: 'LI', name: "O'Higgins" }, { code: 'ML', name: 'Maule' }, { code: 'NB', name: 'Ñuble' },
            { code: 'BI', name: 'Biobío' }, { code: 'AR', name: 'La Araucanía' }, { code: 'LR', name: 'Los Ríos' },
            { code: 'LL', name: 'Los Lagos' }, { code: 'AI', name: 'Aysén' }, { code: 'MA', name: 'Magallanes' },
        ],
    },
    {
        code: 'CO', name: 'Colômbia', flag: '🇨🇴',
        subdivisions: [
            { code: 'AMA', name: 'Amazonas' }, { code: 'ANT', name: 'Antioquia' }, { code: 'ARA', name: 'Arauca' },
            { code: 'ATL', name: 'Atlántico' }, { code: 'BOL', name: 'Bolívar' }, { code: 'BOY', name: 'Boyacá' },
            { code: 'CAL', name: 'Caldas' }, { code: 'CAQ', name: 'Caquetá' }, { code: 'CAS', name: 'Casanare' },
            { code: 'CAU', name: 'Cauca' }, { code: 'CES', name: 'Cesar' }, { code: 'CHO', name: 'Chocó' },
            { code: 'COR', name: 'Córdoba' }, { code: 'CUN', name: 'Cundinamarca' }, { code: 'DC', name: 'Bogotá D.C.' },
            { code: 'GUA', name: 'Guainía' }, { code: 'GUV', name: 'Guaviare' }, { code: 'HUI', name: 'Huila' },
            { code: 'LAG', name: 'La Guajira' }, { code: 'MAG', name: 'Magdalena' }, { code: 'MET', name: 'Meta' },
            { code: 'NAR', name: 'Nariño' }, { code: 'NSA', name: 'Norte de Santander' },
            { code: 'PUT', name: 'Putumayo' }, { code: 'QUI', name: 'Quindío' }, { code: 'RIS', name: 'Risaralda' },
            { code: 'SAP', name: 'San Andrés y Providencia' }, { code: 'SAN', name: 'Santander' },
            { code: 'SUC', name: 'Sucre' }, { code: 'TOL', name: 'Tolima' },
            { code: 'VAC', name: 'Valle del Cauca' }, { code: 'VAU', name: 'Vaupés' }, { code: 'VID', name: 'Vichada' },
        ],
    },
    {
        code: 'PE', name: 'Peru', flag: '🇵🇪',
        subdivisions: [
            { code: 'AMA', name: 'Amazonas' }, { code: 'ANC', name: 'Áncash' }, { code: 'APU', name: 'Apurímac' },
            { code: 'ARE', name: 'Arequipa' }, { code: 'AYA', name: 'Ayacucho' }, { code: 'CAJ', name: 'Cajamarca' },
            { code: 'CAL', name: 'Callao' }, { code: 'CUS', name: 'Cusco' }, { code: 'HUC', name: 'Huánuco' },
            { code: 'HUV', name: 'Huancavelica' }, { code: 'ICA', name: 'Ica' }, { code: 'JUN', name: 'Junín' },
            { code: 'LAL', name: 'La Libertad' }, { code: 'LAM', name: 'Lambayeque' }, { code: 'LIM', name: 'Lima' },
            { code: 'LOR', name: 'Loreto' }, { code: 'MDD', name: 'Madre de Dios' }, { code: 'MOQ', name: 'Moquegua' },
            { code: 'PAS', name: 'Pasco' }, { code: 'PIU', name: 'Piura' }, { code: 'PUN', name: 'Puno' },
            { code: 'SAM', name: 'San Martín' }, { code: 'TAC', name: 'Tacna' }, { code: 'TUM', name: 'Tumbes' },
            { code: 'UCA', name: 'Ucayali' },
        ],
    },
    {
        code: 'PT', name: 'Portugal', flag: '🇵🇹',
        subdivisions: [
            { code: 'AV', name: 'Aveiro' }, { code: 'BE', name: 'Beja' }, { code: 'BR', name: 'Braga' },
            { code: 'BN', name: 'Bragança' }, { code: 'CB', name: 'Castelo Branco' }, { code: 'CO', name: 'Coimbra' },
            { code: 'EV', name: 'Évora' }, { code: 'FA', name: 'Faro' }, { code: 'GU', name: 'Guarda' },
            { code: 'LE', name: 'Leiria' }, { code: 'LI', name: 'Lisboa' }, { code: 'PO', name: 'Portalegre' },
            { code: 'PT', name: 'Porto' }, { code: 'SA', name: 'Santarém' }, { code: 'SE', name: 'Setúbal' },
            { code: 'VC', name: 'Viana do Castelo' }, { code: 'VR', name: 'Vila Real' }, { code: 'VS', name: 'Viseu' },
            { code: 'RA', name: 'Açores' }, { code: 'RM', name: 'Madeira' },
        ],
    },
    {
        code: 'ES', name: 'Espanha', flag: '🇪🇸',
        subdivisions: [
            { code: 'AN', name: 'Andaluzia' }, { code: 'AR', name: 'Aragão' }, { code: 'AS', name: 'Astúrias' },
            { code: 'CB', name: 'Cantábria' }, { code: 'CL', name: 'Castela e Leão' },
            { code: 'CM', name: 'Castela-Mancha' }, { code: 'CN', name: 'Canárias' },
            { code: 'CT', name: 'Catalunha' }, { code: 'EX', name: 'Estremadura' },
            { code: 'GA', name: 'Galícia' }, { code: 'IB', name: 'Ilhas Baleares' },
            { code: 'LR', name: 'La Rioja' }, { code: 'MD', name: 'Madrid' },
            { code: 'MC', name: 'Múrcia' }, { code: 'NC', name: 'Navarra' },
            { code: 'PV', name: 'País Basco' }, { code: 'VC', name: 'Valenciana' },
        ],
    },
    {
        code: 'FR', name: 'França', flag: '🇫🇷',
        subdivisions: [
            { code: 'ARA', name: 'Auvergne-Rhône-Alpes' }, { code: 'BFC', name: 'Bourgogne-Franche-Comté' },
            { code: 'BRE', name: 'Bretanha' }, { code: 'CVL', name: 'Centre-Val de Loire' },
            { code: 'COR', name: 'Córsega' }, { code: 'GES', name: 'Grand Est' },
            { code: 'HDF', name: 'Hauts-de-France' }, { code: 'IDF', name: 'Île-de-France' },
            { code: 'NOR', name: 'Normandia' }, { code: 'NAQ', name: 'Nova Aquitânia' },
            { code: 'OCC', name: 'Occitânia' }, { code: 'PDL', name: 'Pays de la Loire' },
            { code: 'PAC', name: "Provence-Alpes-Côte d'Azur" },
        ],
    },
    {
        code: 'IT', name: 'Itália', flag: '🇮🇹',
        subdivisions: [
            { code: 'ABR', name: 'Abruzzo' }, { code: 'BAS', name: 'Basilicata' }, { code: 'CAL', name: 'Calabria' },
            { code: 'CAM', name: 'Campania' }, { code: 'EMR', name: 'Emilia-Romagna' },
            { code: 'FVG', name: 'Friuli-Venezia Giulia' }, { code: 'LAZ', name: 'Lazio' },
            { code: 'LIG', name: 'Liguria' }, { code: 'LOM', name: 'Lombardia' },
            { code: 'MAR', name: 'Marche' }, { code: 'MOL', name: 'Molise' },
            { code: 'PMN', name: 'Piemonte' }, { code: 'PUG', name: 'Puglia' },
            { code: 'SAR', name: 'Sardenha' }, { code: 'SIC', name: 'Sicília' },
            { code: 'TOS', name: 'Toscana' }, { code: 'TAA', name: 'Trentino-Alto Adige' },
            { code: 'UMB', name: 'Umbria' }, { code: 'VDA', name: "Valle d'Aosta" },
            { code: 'VEN', name: 'Veneto' },
        ],
    },
    {
        code: 'DE', name: 'Alemanha', flag: '🇩🇪',
        subdivisions: [
            { code: 'BB', name: 'Brandemburgo' }, { code: 'BE', name: 'Berlim' }, { code: 'BW', name: 'Baden-Württemberg' },
            { code: 'BY', name: 'Baviera' }, { code: 'HB', name: 'Bremen' }, { code: 'HE', name: 'Hesse' },
            { code: 'HH', name: 'Hamburgo' }, { code: 'MV', name: 'Mecklenburg-Vorpommern' },
            { code: 'NI', name: 'Baixa Saxônia' }, { code: 'NW', name: 'Renânia do Norte-Vestfália' },
            { code: 'RP', name: 'Renânia-Palatinado' }, { code: 'SH', name: 'Schleswig-Holstein' },
            { code: 'SL', name: 'Sarre' }, { code: 'SN', name: 'Saxônia' },
            { code: 'ST', name: 'Saxônia-Anhalt' }, { code: 'TH', name: 'Turíngia' },
        ],
    },
    {
        code: 'GB', name: 'Reino Unido', flag: '🇬🇧',
        subdivisions: [
            { code: 'ENG', name: 'Inglaterra' }, { code: 'SCT', name: 'Escócia' },
            { code: 'WLS', name: 'País de Gales' }, { code: 'NIR', name: 'Irlanda do Norte' },
        ],
    },
    {
        code: 'AU', name: 'Austrália', flag: '🇦🇺',
        subdivisions: [
            { code: 'ACT', name: 'Australian Capital Territory' }, { code: 'NSW', name: 'New South Wales' },
            { code: 'NT', name: 'Northern Territory' }, { code: 'QLD', name: 'Queensland' },
            { code: 'SA', name: 'South Australia' }, { code: 'TAS', name: 'Tasmania' },
            { code: 'VIC', name: 'Victoria' }, { code: 'WA', name: 'Western Australia' },
        ],
    },
    {
        code: 'JP', name: 'Japão', flag: '🇯🇵',
        subdivisions: [
            { code: 'HKD', name: 'Hokkaido' }, { code: 'AOM', name: 'Aomori' }, { code: 'IWT', name: 'Iwate' },
            { code: 'MYG', name: 'Miyagi' }, { code: 'AKT', name: 'Akita' }, { code: 'YGT', name: 'Yamagata' },
            { code: 'FKS', name: 'Fukushima' }, { code: 'IBR', name: 'Ibaraki' }, { code: 'TCG', name: 'Tochigi' },
            { code: 'GNM', name: 'Gunma' }, { code: 'STM', name: 'Saitama' }, { code: 'CHB', name: 'Chiba' },
            { code: 'TKY', name: 'Tóquio' }, { code: 'KNG', name: 'Kanagawa' }, { code: 'NGT', name: 'Niigata' },
            { code: 'TYM', name: 'Toyama' }, { code: 'ISK', name: 'Ishikawa' }, { code: 'FKI', name: 'Fukui' },
            { code: 'YMN', name: 'Yamanashi' }, { code: 'NGN', name: 'Nagano' }, { code: 'SZK', name: 'Shizuoka' },
            { code: 'AIC', name: 'Aichi' }, { code: 'MIE', name: 'Mie' }, { code: 'SHG', name: 'Shiga' },
            { code: 'KYT', name: 'Quioto' }, { code: 'OSK', name: 'Osaka' }, { code: 'HYG', name: 'Hyogo' },
            { code: 'NRA', name: 'Nara' }, { code: 'WKY', name: 'Wakayama' }, { code: 'TTR', name: 'Tottori' },
            { code: 'SMN', name: 'Shimane' }, { code: 'OKY', name: 'Okayama' }, { code: 'HRS', name: 'Hiroshima' },
            { code: 'YGC', name: 'Yamaguchi' }, { code: 'TKS', name: 'Tokushima' }, { code: 'KGW', name: 'Kagawa' },
            { code: 'EHM', name: 'Ehime' }, { code: 'KCH', name: 'Kochi' }, { code: 'FKO', name: 'Fukuoka' },
            { code: 'SGA', name: 'Saga' }, { code: 'NGS', name: 'Nagasaki' }, { code: 'KMT', name: 'Kumamoto' },
            { code: 'OIT', name: 'Oita' }, { code: 'MYZ', name: 'Miyazaki' }, { code: 'KGS', name: 'Kagoshima' },
            { code: 'OKN', name: 'Okinawa' },
        ],
    },
    { code: 'AF', name: 'Afeganistão', flag: '🇦🇫', subdivisions: [] },
    { code: 'AL', name: 'Albânia', flag: '🇦🇱', subdivisions: [] },
    { code: 'DZ', name: 'Argélia', flag: '🇩🇿', subdivisions: [] },
    { code: 'AO', name: 'Angola', flag: '🇦🇴', subdivisions: [] },
    { code: 'AT', name: 'Áustria', flag: '🇦🇹', subdivisions: [] },
    { code: 'BE', name: 'Bélgica', flag: '🇧🇪', subdivisions: [] },
    { code: 'BO', name: 'Bolívia', flag: '🇧🇴', subdivisions: [] },
    { code: 'BA', name: 'Bósnia e Herzegovina', flag: '🇧🇦', subdivisions: [] },
    { code: 'CV', name: 'Cabo Verde', flag: '🇨🇻', subdivisions: [] },
    { code: 'CM', name: 'Camarões', flag: '🇨🇲', subdivisions: [] },
    { code: 'CN', name: 'China', flag: '🇨🇳', subdivisions: [] },
    { code: 'CY', name: 'Chipre', flag: '🇨🇾', subdivisions: [] },
    { code: 'HR', name: 'Croácia', flag: '🇭🇷', subdivisions: [] },
    { code: 'CU', name: 'Cuba', flag: '🇨🇺', subdivisions: [] },
    { code: 'DK', name: 'Dinamarca', flag: '🇩🇰', subdivisions: [] },
    { code: 'EC', name: 'Equador', flag: '🇪🇨', subdivisions: [] },
    { code: 'EG', name: 'Egito', flag: '🇪🇬', subdivisions: [] },
    { code: 'SV', name: 'El Salvador', flag: '🇸🇻', subdivisions: [] },
    { code: 'FI', name: 'Finlândia', flag: '🇫🇮', subdivisions: [] },
    { code: 'GH', name: 'Gana', flag: '🇬🇭', subdivisions: [] },
    { code: 'GR', name: 'Grécia', flag: '🇬🇷', subdivisions: [] },
    { code: 'GT', name: 'Guatemala', flag: '🇬🇹', subdivisions: [] },
    { code: 'HT', name: 'Haiti', flag: '🇭🇹', subdivisions: [] },
    { code: 'HN', name: 'Honduras', flag: '🇭🇳', subdivisions: [] },
    { code: 'HK', name: 'Hong Kong', flag: '🇭🇰', subdivisions: [] },
    { code: 'IN', name: 'Índia', flag: '🇮🇳', subdivisions: [] },
    { code: 'ID', name: 'Indonésia', flag: '🇮🇩', subdivisions: [] },
    { code: 'IE', name: 'Irlanda', flag: '🇮🇪', subdivisions: [] },
    { code: 'IL', name: 'Israel', flag: '🇮🇱', subdivisions: [] },
    { code: 'JM', name: 'Jamaica', flag: '🇯🇲', subdivisions: [] },
    { code: 'KE', name: 'Quênia', flag: '🇰🇪', subdivisions: [] },
    { code: 'KR', name: 'Coreia do Sul', flag: '🇰🇷', subdivisions: [] },
    { code: 'LB', name: 'Líbano', flag: '🇱🇧', subdivisions: [] },
    { code: 'LU', name: 'Luxemburgo', flag: '🇱🇺', subdivisions: [] },
    { code: 'MY', name: 'Malásia', flag: '🇲🇾', subdivisions: [] },
    { code: 'MT', name: 'Malta', flag: '🇲🇹', subdivisions: [] },
    { code: 'MA', name: 'Marrocos', flag: '🇲🇦', subdivisions: [] },
    { code: 'MZ', name: 'Moçambique', flag: '🇲🇿', subdivisions: [] },
    { code: 'NL', name: 'Países Baixos', flag: '🇳🇱', subdivisions: [] },
    { code: 'NZ', name: 'Nova Zelândia', flag: '🇳🇿', subdivisions: [] },
    { code: 'NG', name: 'Nigéria', flag: '🇳🇬', subdivisions: [] },
    { code: 'NO', name: 'Noruega', flag: '🇳🇴', subdivisions: [] },
    { code: 'PK', name: 'Paquistão', flag: '🇵🇰', subdivisions: [] },
    { code: 'PA', name: 'Panamá', flag: '🇵🇦', subdivisions: [] },
    { code: 'PY', name: 'Paraguai', flag: '🇵🇾', subdivisions: [] },
    { code: 'PH', name: 'Filipinas', flag: '🇵🇭', subdivisions: [] },
    { code: 'PL', name: 'Polônia', flag: '🇵🇱', subdivisions: [] },
    { code: 'PR', name: 'Porto Rico', flag: '🇵🇷', subdivisions: [] },
    { code: 'RO', name: 'Romênia', flag: '🇷🇴', subdivisions: [] },
    { code: 'RU', name: 'Rússia', flag: '🇷🇺', subdivisions: [] },
    { code: 'SA', name: 'Arábia Saudita', flag: '🇸🇦', subdivisions: [] },
    { code: 'SN', name: 'Senegal', flag: '🇸🇳', subdivisions: [] },
    { code: 'SG', name: 'Singapura', flag: '🇸🇬', subdivisions: [] },
    { code: 'ZA', name: 'África do Sul', flag: '🇿🇦', subdivisions: [] },
    { code: 'SE', name: 'Suécia', flag: '🇸🇪', subdivisions: [] },
    { code: 'CH', name: 'Suíça', flag: '🇨🇭', subdivisions: [] },
    { code: 'TW', name: 'Taiwan', flag: '🇹🇼', subdivisions: [] },
    { code: 'TH', name: 'Tailândia', flag: '🇹🇭', subdivisions: [] },
    { code: 'TN', name: 'Tunísia', flag: '🇹🇳', subdivisions: [] },
    { code: 'TR', name: 'Turquia', flag: '🇹🇷', subdivisions: [] },
    { code: 'UA', name: 'Ucrânia', flag: '🇺🇦', subdivisions: [] },
    { code: 'AE', name: 'Emirados Árabes Unidos', flag: '🇦🇪', subdivisions: [] },
    { code: 'UY', name: 'Uruguai', flag: '🇺🇾', subdivisions: [] },
    { code: 'VE', name: 'Venezuela', flag: '🇻🇪', subdivisions: [] },
    { code: 'VN', name: 'Vietnã', flag: '🇻🇳', subdivisions: [] },
    { code: 'ZM', name: 'Zâmbia', flag: '🇿🇲', subdivisions: [] },
    { code: 'ZW', name: 'Zimbábue', flag: '🇿🇼', subdivisions: [] },
]

export function getCountry(code: string): GeoCountry | undefined {
    return GEO_COUNTRIES.find(c => c.code === code)
}
